### PR TITLE
Rw debug

### PR DESCRIPTION
**Pull request by rosewisotzky**
# Description

Fixed bug so the home page list only shows the top 20 most recently added products that are active.

Fixes Issue # (link issue ticket here)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

`git checkout master`
`git fetch --all`
`git checkout rw-debug`
`cd BangazonSite`
`start BangazonSite.sln`
Click on Sell New Product
Create a new product to sell
Go to Home page
are there 20 items and yours is on top? Cool!
now delete that new product
go back to home page
Is it gone?
Very good.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by wemitchell3 — APPROVED** [review]
Tested works. Good to go.

**Review by wlmathison — APPROVED** [review]
Very Nice.

**Review by bluemorgan23 — CHANGES_REQUESTED** [review]
The home list for some reason is listing text below the link that shouldn't be there. Not sure if this is just on my machine or not

**Review by bluemorgan23 — APPROVED** [review]
Thanks for fixing that!

**Pull request merged**
