### PR TITLE
Adding MyIndex method on ProductController to display users products. …

### PR DESCRIPTION
**Pull request by wlmathison**
# Description
Adding MyIndex method on ProductController to display users products. Removing edit and delete links for all products and adding them to only display for users products. Adding My Products to navbar. Adding functionality to only allow users to edit/delete their own products

Also - only displaying active products.

Fixes Issue [#11](https://github.com/the-devastating-chickens/BangazonSite/issues/11)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Testing Instructions

1.  `git fetch --all`
1. `git checkout wlm-remove-product-listing`
1. Run Bangazon project
1. Navigate to My Products on navbar.
1. If you have created products make sure that they are displayed and only them.
1. If you have not created any products do so now.
1. Delete one of your products and verify that it if it was attached to an order then it has been deleted from the db and that if it was attached to an order verify that it is still in the db but that active property is now false. Verify that either way it does not show on any product view.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by wemitchell3 — APPROVED** [review]
Reviewed your code. Added product, logged out and logged in as a different user and I was not able to see the product. Was also able to delete. Works correctly.

**Review by anneraev — APPROVED** [review]
It works! I only saw my one product and I was able to delete it and then it was gone. I couldn't see it as the test user.

**Review by bluemorgan23 — APPROVED** [review]
Looks good!

**Review by wemitchell3 — APPROVED** [review]
Reviewed code. Tested features. All works and info was updated in the DB. Good to go.

**Pull request merged**
